# Generated by Django 3.1.5 on 2021-01-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_ban'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BAN',
        ),
    ]
